name: BuddeeUp
description: Social Network App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_native_splash: ^2.2.19
  carousel_slider: ^4.2.1
  provider: ^6.0.5
  font_awesome_flutter: ^10.4.0
  intl_phone_field: ^3.1.0
  email_validator: ^2.1.17
  flutter_markdown: ^0.6.17+3
  flutter_svg: ^2.0.7
  pin_code_fields: ^8.0.1
  dotted_border: ^2.0.0+3
  http: ^1.1.0
  country_code_picker: ^3.0.0
  choice: ^2.0.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  permission_handler: ^11.0.0
  image_picker: ^1.0.4
  google_sign_in: ^6.1.5
  logger: ^2.0.2+1
  flutter_facebook_auth: ^6.0.2
  shared_preferences: ^2.2.1
  json_annotation: ^4.8.1
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2
  flutter_timer_countdown: ^1.0.5
  timeago: ^3.5.0
  datepicker_dropdown: ^0.0.8
  intl_phone_number_input: ^0.7.3+1
  chat_bubbles: ^1.5.0
  another_flutter_splash_screen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  intl: ^0.18.1

flutter:
  uses-material-design: true

  assets:
    - "assets/images/"
    - "assets/dps/"

