name: BuddeeUp
description: Social Network App.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_native_splash: ^2.2.19
  carousel_slider: ^4.2.1
  provider: ^6.0.5
  font_awesome_flutter: ^10.4.0
  intl_phone_field: ^3.1.0
  email_validator: ^2.1.17
  flutter_markdown: ^0.6.17+3
  flutter_svg: ^2.0.7
  pin_code_fields: ^8.0.1
  dotted_border: ^2.0.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


flutter_native_splash:
  color: "#DA3EE8"
  color_dark: "#DA3EE8"
  image: "assets/images/buddeeup_splash.png"
  image_dark: "assets/images/buddeeup_splash.png"

  android_12:
    image: "assets/images/buddeeup_splash.png"
    icon_background_color: "#DA3EE8"
    image_dark: "assets/images/buddeeup_splash.png"
    icon_background_color_dark: "#DA3EE8"
  flutter_lints: ^2.0.0

  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - "assets/images/buddee_up_logo.png"
    - "assets/images/Ellipse3.png"
    - "assets/images/Frame3.png"
    - "assets/images/Frame4.png"
    - "assets/images/Ellipse4.png"
    - "assets/images/Ellipse3.svg"
    - "assets/images/Frame3.svg"
    - "assets/images/flat-color-icons_google.png"
    - "assets/images/logos_facebook.png"
    - "assets/images/instagram1.png"
    - "assets/images/User1.png"
    - "assets/images/User2.png"
    - "assets/images/ri_compass-discover-fill.png"
    - "assets/images/mi_filter.png"
    - "assets/images/photo.png"
    - "assets/images/photo.png"
    - "assets/images/photo1.png"
    - "assets/images/photo2.png"
    - "assets/images/photo3.png"
    - "assets/images/photo4.png"
    - "assets/images/buddee_up_splash_logo.png"
    - "assets/images/buddeeup_splash.png"
    - "assets/images/green status.png"
    - "assets/images/person1.jpeg"
    - "assets/images/person2.jpeg"
    - "assets/images/person3.jpeg"
    - "assets/images/person4.jpeg"
    - "assets/images/person5.jpeg"
    - "assets/images/cancel.png"
    - "assets/images/ps_tribe.jpg"
    - "assets/images/carbon_friendship.jpg"
    - "assets/images/annabelle.png"
    - "assets/images/cafetalksImage.png"



flutter_icons:
  android: true
  ios: true
  web: true
  image_path_android: "assets/images/buddee_up_logo.png"
  image_path_ios: "assets/images/buddee_up_logo.png"



